apiVersion: v1
kind: Service
metadata:
  name: {{ include "vectorizer.fullname" . }}
  labels:
    {{- include "vectorizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.replicationPort }}
      targetPort: replication
      protocol: TCP
      name: replication
  selector:
    {{- include "vectorizer.selectorLabels" . | nindent 4 }}

